language java
words kwroot miss=plain {
  synchronized:keyword:1 abstract:keyword:1 private:keyword:1 var:keyword:1 static:keyword:1 if:keyword:0 "const ":keyword:1 for:keyword:0 while:keyword:1 strictfp:keyword:1 finally:keyword:1 protected:keyword:1 import:keyword:1 native:keyword:1 final:keyword:1 void:keyword:1 enum:keyword:1 else:keyword:1 break:keyword:1 transient:keyword:1 catch:keyword:1 instanceof:keyword:1 volatile:keyword:1 case:keyword:1 assert:keyword:1 package:keyword:1 default:keyword:1 public:keyword:1 try:keyword:1 switch:keyword:1 continue:keyword:1 throws:keyword:1 module:keyword:1 requires:keyword:1 exports:keyword:1 do:keyword:1 sealed:keyword:1 yield:keyword:1 permits:keyword:1 goto:keyword:1 when:keyword:1 false:literal:1 true:literal:1 null:literal:1 char:type:1 boolean:type:1 long:type:1 float:type:1 int:type:1 byte:type:1 short:type:1 double:type:1 super:built_in:1 this:built_in:1
}
words kw6 miss=plain {
  import:keyword:1
}
words kw33 miss=plain {
  new:keyword:1 throw:keyword:1 return:keyword:1 else:keyword:1
}
rule eng3 { " " " "* eng3sep eng3sep eng3sep }
rule eng3sep { eng3w "."? ":"? ( "." " " / " " ) }
rule eng3w { eng3con / eng3hyp / eng3short / eng3cap }
rule eng3con { [A-Za-z] [A-Za-z]* "'" ( "d" / "ve" / "re" / "ll" / "t" / "s" / "n" ) }
rule eng3hyp { [A-Za-z] [A-Za-z]* "-" [a-z] [a-z]* }
rule eng3short { ( "is" / "so" / "us" / "to" / "at" / "if" / "in" / "it" / "on" / "I" / "a" ) ![A-Za-z] }
rule eng3cap { [A-Za-z] [a-z] [a-z] [a-z]* }
rule __kwscanpat_kw6 { [0-9A-Z_a-z] [0-9A-Z_a-z]* }
rule __kwscanpat_kwroot { [0-9A-Z_a-z] [0-9A-Z_a-z]* }
rule mc34_r0 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" mc34_r0 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* mc34_r0 / ">" }
rule mc34_r1 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" mc34_r1 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* mc34_r1 / ">" }
rule mc34_r2 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" mc34_r2 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* mc34_r2 / ">" }
rule mc34_r3 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" mc34_r3 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* mc34_r3 / ">" }
rule mc34_r4 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" mc34_r2 mc34_r4 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* mc34_r3 mc34_r4 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* mc34_r4 / ">" [\t-\r ] [\t-\r ]* cap scope=title.function rel=0 mc=1 { [A-Z_a-z] [0-9A-Z_a-z]* } [\t-\r ]* &"(" }
rule mc34_r5 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" mc34_r5 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* mc34_r5 / ">" &mc34_r4 }
rule mc34_r6 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" mc34_r6 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* mc34_r6 / ">" }
rule mc34_r7 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" mc34_r7 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* mc34_r7 / ">" }
rule mc34_r8 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" mc34_r8 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* mc34_r8 / ">" }
rule mc34_r9 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" mc34_r9 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* mc34_r9 / ">" }
rule mc34_r10 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" mc34_r8 mc34_r10 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* mc34_r9 mc34_r10 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* mc34_r10 / ">" &( [\t-\r ] [\t-\r ]* cap scope=title.function rel=0 mc=1 { [A-Z_a-z] [0-9A-Z_a-z]* } [\t-\r ]* &"(" ) }
rule h_r11 { "_"* [0-9] h_r11 / ( ( [DFdf] ![a-zA-Z0-9_] / ( ( !nb [a-zA-Z0-9_] ![a-zA-Z0-9_] / nb [a-zA-Z0-9_] &[a-zA-Z0-9_] ) ) ) ) }
rule h_r12 { "_"* [0-9] h_r12 / ( ( [DFdf] ![a-zA-Z0-9_] / ( ( !nb [a-zA-Z0-9_] ![a-zA-Z0-9_] / nb [a-zA-Z0-9_] &[a-zA-Z0-9_] ) ) ) ) }
rule h_r13 { "_"* [0-9] h_r13 / ( ( [DFdf] ![a-zA-Z0-9_] / ( ( !nb [a-zA-Z0-9_] ![a-zA-Z0-9_] / nb [a-zA-Z0-9_] &[a-zA-Z0-9_] ) ) ) ) }
rule h_r14 { "_"* [0-9] h_r14 / ( ( [DFdf] ![a-zA-Z0-9_] / ( ( !nb [a-zA-Z0-9_] ![a-zA-Z0-9_] / nb [a-zA-Z0-9_] &[a-zA-Z0-9_] ) ) ) ) }
rule h_r15 { "_"* [0-9] h_r15 / ( ( [DFdf] ![a-zA-Z0-9_] / ( ( !nb [a-zA-Z0-9_] ![a-zA-Z0-9_] / nb [a-zA-Z0-9_] &[a-zA-Z0-9_] ) ) ) ) }
rule h_r16 { "_"* [0-9] h_r16 / ( ( [DFdf] ![a-zA-Z0-9_] / ( ( !nb [a-zA-Z0-9_] ![a-zA-Z0-9_] / nb [a-zA-Z0-9_] &[a-zA-Z0-9_] ) ) ) ) }
rule h_r17 { "_"* [0-9] h_r17 / ( ( [DFdf] ![a-zA-Z0-9_] / ( ( !nb [a-zA-Z0-9_] ![a-zA-Z0-9_] / nb [a-zA-Z0-9_] &[a-zA-Z0-9_] ) ) ) ) }
rule h_r18 { "_"* [0-9] h_r18 / ( ( [DFdf] ![a-zA-Z0-9_] / ( ( !nb [a-zA-Z0-9_] ![a-zA-Z0-9_] / nb [a-zA-Z0-9_] &[a-zA-Z0-9_] ) ) ) ) }
rule h_r19 { "_"* [0-9] h_r19 / ( ( [Ll] ![a-zA-Z0-9_] / ( ( !nb [a-zA-Z0-9_] ![a-zA-Z0-9_] / nb [a-zA-Z0-9_] &[a-zA-Z0-9_] ) ) ) ) }
rule h_r20 { "_"* [0-9A-Fa-f] h_r20 / ( ( [Ll] ![a-zA-Z0-9_] / ( ( !nb [a-zA-Z0-9_] ![a-zA-Z0-9_] / nb [a-zA-Z0-9_] &[a-zA-Z0-9_] ) ) ) ) }
rule h_r21 { "_"* [0-7] h_r21 / ( ( [Ll] ![a-zA-Z0-9_] / ( ( !nb [a-zA-Z0-9_] ![a-zA-Z0-9_] / nb [a-zA-Z0-9_] &[a-zA-Z0-9_] ) ) ) ) }
rule h_r22 { "_"* [01] h_r22 / ( ( [Ll] ![a-zA-Z0-9_] / ( ( !nb [a-zA-Z0-9_] ![a-zA-Z0-9_] / nb [a-zA-Z0-9_] &[a-zA-Z0-9_] ) ) ) ) }
rule kig_r23 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" kig_r23 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* kig_r23 / ">" }
rule kig_r24 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" kig_r24 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* kig_r24 / ">" }
rule kig_r25 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" kig_r25 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* kig_r25 / ">" }
rule kig_r26 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" kig_r26 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* kig_r26 / ">" }
rule kig_r27 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" kig_r25 kig_r27 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* kig_r26 kig_r27 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* kig_r27 / ">" [\t-\r ] [\t-\r ]* [A-Z_a-z] [0-9A-Z_a-z]* [\t-\r ]* &"(" }
rule kig_r28 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" kig_r28 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* kig_r28 / ">" &kig_r27 }
rule kig_r29 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" kig_r29 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* kig_r29 / ">" }
rule kig_r30 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" kig_r30 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* kig_r30 / ">" }
rule kig_r31 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" kig_r31 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* kig_r31 / ">" }
rule kig_r32 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" kig_r32 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* kig_r32 / ">" }
rule kig_r33 { [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" kig_r31 kig_r33 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* kig_r32 kig_r33 / [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* kig_r33 / ">" &( [\t-\r ] [\t-\r ]* [A-Z_a-z] [0-9A-Z_a-z]* [\t-\r ]* &"(" ) }
rule m0 scope=comment rel=0 { "/**" ( m1 / m2 / m3 / m4 / !( "*/" ) any )* ( "*/" / eoftrunc ) }
rule m1 rel=0 { [0-9A-Z_a-z] [0-9A-Z_a-z]* "@" }
rule m2 scope=doctag rel=1 { "@" [A-Za-z] [A-Za-z]* }
rule m3 rel=0 { [ ]* cap scope=doctag rel=0 { ( "TODO" / "FIXME" / "NOTE" / "BUG" / "OPTIMIZE" / "HACK" / "XXX" ) ":" } }
rule m4 rel=1 { eng3 }
rule m0__resume { ( m1 / m2 / m3 / m4 / !( "*/" ) any )* ( "*/" / eoftrunc ) }
rule m5 rel=2 { kwscan kw6 __kwscanpat_kw6 { "import java." [a-z] [a-z]* "." } }
rule m6 scope=comment rel=0 { "//" ( m7 / m8 / !( &( [\n\r] / eof ) ) any )* ( rel(1){ &( [\n\r] / eof ) } / eoftrunc ) }
rule m7 rel=0 { [ ]* cap scope=doctag rel=0 { ( "TODO" / "FIXME" / "NOTE" / "BUG" / "OPTIMIZE" / "HACK" / "XXX" ) ":" } }
rule m8 rel=1 { eng3 }
rule m6__resume { ( m7 / m8 / !( &( [\n\r] / eof ) ) any )* ( rel(1){ &( [\n\r] / eof ) } / eoftrunc ) }
rule m9 scope=comment rel=0 { "/*" ( m10 / m11 / !( "*/" ) any )* ( rel(1){ "*/" } / eoftrunc ) }
rule m10 rel=0 { [ ]* cap scope=doctag rel=0 { ( "TODO" / "FIXME" / "NOTE" / "BUG" / "OPTIMIZE" / "HACK" / "XXX" ) ":" } }
rule m11 rel=1 { eng3 }
rule m9__resume { ( m10 / m11 / !( "*/" ) any )* ( rel(1){ "*/" } / eoftrunc ) }
rule m12 scope=string rel=0 { "\"\"\"" ( m13 / !"\"\"\"" any )* ( rel(1){ "\"\"\"" } / eoftrunc ) }
rule m13 rel=0 { "\\" any }
rule m12__resume { ( m13 / !"\"\"\"" any )* ( rel(1){ "\"\"\"" } / eoftrunc ) }
rule m14 scope=string rel=0 { "'" ( m15 / !"'" illegalx { "\n" } / !"'" any )* ( rel(1){ "'" } / eoftrunc ) }
rule m15 rel=0 { "\\" any }
rule m14__resume { ( m15 / !"'" illegalx { "\n" } / !"'" any )* ( rel(1){ "'" } / eoftrunc ) }
rule m16 scope=string rel=0 { "\"" ( m17 / !"\"" illegalx { "\n" } / !"\"" any )* ( rel(1){ "\"" } / eoftrunc ) }
rule m17 rel=0 { "\\" any }
rule m16__resume { ( m17 / !"\"" illegalx { "\n" } / !"\"" any )* ( rel(1){ "\"" } / eoftrunc ) }
rule m18 rel=1 { cap scope=keyword rel=0 mc=1 { nb [a-zA-Z0-9_] ( "class" / "interface" / "enum" / "extends" / "implements" / "new" ) } [\t-\r ] [\t-\r ]* cap scope=title.class rel=0 mc=1 { [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* } }
rule m19 scope=keyword rel=1 { "non-sealed" }
rule m20 rel=1 { cap scope=type rel=0 mc=1 { !"else" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* } [\t-\r ] [\t-\r ]* cap scope=variable rel=0 mc=1 { [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* } [\t-\r ] [\t-\r ]* cap scope=operator rel=0 mc=1 { "=" !"=" } }
rule m21 rel=0 { cap scope=keyword rel=0 mc=1 { "record" } [\t-\r ] [\t-\r ]* cap scope=title.class rel=0 mc=1 { [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* } ( !( "(" ) m22 / !( "(" ) m25 )*  ( m28 )? rel(1){ &( any / eof ) } }
rule m22 scope=comment rel=0 { "//" ( m23 / m24 / !( &( [\n\r] / eof ) ) any )* ( rel(1){ &( [\n\r] / eof ) } / eoftrunc ) }
rule m23 rel=0 { [ ]* cap scope=doctag rel=0 { ( "TODO" / "FIXME" / "NOTE" / "BUG" / "OPTIMIZE" / "HACK" / "XXX" ) ":" } }
rule m24 rel=1 { eng3 }
rule m22__resume { ( m23 / m24 / !( &( [\n\r] / eof ) ) any )* ( rel(1){ &( [\n\r] / eof ) } / eoftrunc ) }
rule m25 scope=comment rel=0 { "/*" ( m26 / m27 / !( "*/" ) any )* ( rel(1){ "*/" } / eoftrunc ) }
rule m26 rel=0 { [ ]* cap scope=doctag rel=0 { ( "TODO" / "FIXME" / "NOTE" / "BUG" / "OPTIMIZE" / "HACK" / "XXX" ) ":" } }
rule m27 rel=1 { eng3 }
rule m25__resume { ( m26 / m27 / !( "*/" ) any )* ( rel(1){ "*/" } / eoftrunc ) }
rule m28 scope=params rel=0 { "(" ( m29 / !")" kw kwroot { [0-9A-Z_a-z] [0-9A-Z_a-z]* } / !")" any )* ( ")" / eoftrunc ) }
rule m29 scope=comment rel=0 { "/*" ( m30 / m31 / !( "*/" ) any )* ( rel(1){ "*/" } / eoftrunc ) }
rule m30 rel=0 { [ ]* cap scope=doctag rel=0 { ( "TODO" / "FIXME" / "NOTE" / "BUG" / "OPTIMIZE" / "HACK" / "XXX" ) ":" } }
rule m31 rel=1 { eng3 }
rule m29__resume { ( m30 / m31 / !( "*/" ) any )* ( rel(1){ "*/" } / eoftrunc ) }
rule m28__resume { ( m29 / !")" kw kwroot { [0-9A-Z_a-z] [0-9A-Z_a-z]* } / !")" any )* ( ")" / eoftrunc ) }
rule m32 rel=0 { &( nb [a-zA-Z0-9_] ( "new" / "throw" / "return" / "else" ) !"." &( ( ( !nb [a-zA-Z0-9_] ![a-zA-Z0-9_] / nb [a-zA-Z0-9_] &[a-zA-Z0-9_] ) / [\t-\r ] ) ) ) kw kw33 { [0-9A-Z_a-z] [0-9A-Z_a-z]* } }
rule m33 rel=0 { kwscan kwroot __kwscanpat_kwroot { [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" )? mc34_r5 )? mc34_r10 )? [\t-\r ] [\t-\r ]* } cap scope=title.function rel=0 mc=1 { [A-Z_a-z] [0-9A-Z_a-z]* } [\t-\r ]* &"(" ( m34 / m53 / m56 )*  rel(1){ &( any / eof ) } }
rule m34 scope=params rel=0 { "(" ( m35 / m37 / m39 / m41 / m42 / m43 / m44 / m45 / m46 / m47 / m48 / m49 / m50 / !")" kw kwroot { [0-9A-Z_a-z] [0-9A-Z_a-z]* } / !")" any )* ( ")" / eoftrunc ) }
rule m35 scope=meta rel=0 { "@" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( m36 )*  rel(1){ &( any / eof ) } }
rule m36 rel=0 { "(" ( m36 / !")" any )* ( rel(1){ ")" } / eoftrunc ) }
rule m36__resume { ( m36 / !")" any )* ( rel(1){ ")" } / eoftrunc ) }
rule m37 scope=string rel=0 { "'" ( m38 / !"'" illegalx { "\n" } / !"'" any )* ( rel(1){ "'" } / eoftrunc ) }
rule m38 rel=0 { "\\" any }
rule m37__resume { ( m38 / !"'" illegalx { "\n" } / !"'" any )* ( rel(1){ "'" } / eoftrunc ) }
rule m39 scope=string rel=0 { "\"" ( m40 / !"\"" illegalx { "\n" } / !"\"" any )* ( rel(1){ "\"" } / eoftrunc ) }
rule m40 rel=0 { "\\" any }
rule m39__resume { ( m40 / !"\"" illegalx { "\n" } / !"\"" any )* ( rel(1){ "\"" } / eoftrunc ) }
rule m41 scope=number rel=0 { ( ( nb [a-zA-Z0-9_] [0-9] ( "_"* [0-9] )* ( "." [0-9] ( "_"* [0-9] )* [Ee] [+\-]? [0-9] h_r11 / "." [Ee] [+\-]? [0-9] h_r12 / [Ee] [+\-]? [0-9] h_r13 ) ) / "." [0-9] ( "_"* [0-9] )* [Ee] [+\-]? [0-9] h_r14 ) }
rule m42 scope=number rel=0 { nb [a-zA-Z0-9_] [0-9] ( "_"* [0-9] )* ( "." [0-9] h_r15 / "." ( [DFdf] ![a-zA-Z0-9_] )? ) }
rule m43 scope=number rel=0 { "." [0-9] h_r16 }
rule m44 scope=number rel=0 { nb [a-zA-Z0-9_] [0-9] ( "_"* [0-9] )* [DFdf] ![a-zA-Z0-9_] }
rule m45 scope=number rel=0 { nb [a-zA-Z0-9_] "0" [Xx] ( [0-9A-Fa-f] ( "_"* [0-9A-Fa-f] )* "."? [Pp] [+\-]? [0-9] h_r17 / ( [0-9A-Fa-f] ( "_"* [0-9A-Fa-f] )* )? "." [0-9A-Fa-f] ( "_"* [0-9A-Fa-f] )* [Pp] [+\-]? [0-9] h_r18 ) }
rule m46 scope=number rel=0 { nb [a-zA-Z0-9_] ( ( "0" ( [Ll] ![a-zA-Z0-9_] / ![a-zA-Z0-9_] ) ) / [1-9] h_r19 ) }
rule m47 scope=number rel=0 { nb [a-zA-Z0-9_] "0" [Xx] [0-9A-Fa-f] h_r20 }
rule m48 scope=number rel=0 { nb [a-zA-Z0-9_] "0" h_r21 }
rule m49 scope=number rel=0 { nb [a-zA-Z0-9_] "0" [Bb] [01] h_r22 }
rule m50 scope=comment rel=0 { "/*" ( m51 / m52 / !( "*/" ) any )* ( rel(1){ "*/" } / eoftrunc ) }
rule m51 rel=0 { [ ]* cap scope=doctag rel=0 { ( "TODO" / "FIXME" / "NOTE" / "BUG" / "OPTIMIZE" / "HACK" / "XXX" ) ":" } }
rule m52 rel=1 { eng3 }
rule m50__resume { ( m51 / m52 / !( "*/" ) any )* ( rel(1){ "*/" } / eoftrunc ) }
rule m34__resume { ( m35 / m37 / m39 / m41 / m42 / m43 / m44 / m45 / m46 / m47 / m48 / m49 / m50 / !")" kw kwroot { [0-9A-Z_a-z] [0-9A-Z_a-z]* } / !")" any )* ( ")" / eoftrunc ) }
rule m53 scope=comment rel=0 { "//" ( m54 / m55 / !( &( [\n\r] / eof ) ) any )* ( rel(1){ &( [\n\r] / eof ) } / eoftrunc ) }
rule m54 rel=0 { [ ]* cap scope=doctag rel=0 { ( "TODO" / "FIXME" / "NOTE" / "BUG" / "OPTIMIZE" / "HACK" / "XXX" ) ":" } }
rule m55 rel=1 { eng3 }
rule m53__resume { ( m54 / m55 / !( &( [\n\r] / eof ) ) any )* ( rel(1){ &( [\n\r] / eof ) } / eoftrunc ) }
rule m56 scope=comment rel=0 { "/*" ( m57 / m58 / !( "*/" ) any )* ( rel(1){ "*/" } / eoftrunc ) }
rule m57 rel=0 { [ ]* cap scope=doctag rel=0 { ( "TODO" / "FIXME" / "NOTE" / "BUG" / "OPTIMIZE" / "HACK" / "XXX" ) ":" } }
rule m58 rel=1 { eng3 }
rule m56__resume { ( m57 / m58 / !( "*/" ) any )* ( rel(1){ "*/" } / eoftrunc ) }
rule root { ( m0 / m5 / m6 / m9 / m12 / m14 / m16 / m18 / m19 / m20 / m21 / m32 / m33 / m41 / m42 / m43 / m44 / m45 / m46 / m47 / m48 / m49 / m35 / illegalx { ( "</" / "#" ) } / kw kwroot { ( !( "import java." [a-z] [a-z]* "." / "non-sealed" / !"else" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* [\t-\r ] [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* [\t-\r ] [\t-\r ]* "=" !"=" / "record" [\t-\r ] [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* / [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( "<" [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* ( [\t-\r ]* "," [\t-\r ]* [$A-Z_a-z\u] [$0-9A-Z_a-z\u]* )* ">" )? kig_r28 )? kig_r33 )? [\t-\r ] [\t-\r ]* [A-Z_a-z] [0-9A-Z_a-z]* [\t-\r ]* &"(" ) [0-9A-Z_a-z] )+ } / any )* eof }
